# Generated by Django 4.0.5 on 2022-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_mysubscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('visits', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MySubscribers',
        ),
    ]
