# Generated by Django 4.0.5 on 2022-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_chart_delete_mysubscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('howMuch', models.IntegerField(default=5)),
                ('aboute', models.TextField(max_length=700)),
            ],
        ),
    ]
