# Generated by Django 4.0.5 on 2022-06-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
