# Generated by Django 4.0.5 on 2022-06-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Img',
            new_name='img',
        ),
    ]
