# Generated by Django 4.0.5 on 2022-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_img_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Aboute',
            field=models.TextField(max_length=700),
        ),
    ]
